/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppToolbar: typeof import('./components/AppToolbar.vue')['default']
    BatchReservationForm: typeof import('./components/reservation/BatchReservationForm.vue')['default']
    CalendarGrid: typeof import('./components/calendar/CalendarGrid.vue')['default']
    CalendarToolbar: typeof import('./components/calendar/CalendarToolbar.vue')['default']
    ConfirmDialog: typeof import('./components/ui/ConfirmDialog.vue')['default']
    DeviceCard: typeof import('./components/device/DeviceCard.vue')['default']
    DeviceDeleteDialog: typeof import('./components/device/DeviceDeleteDialog.vue')['default']
    DeviceForm: typeof import('./components/device/DeviceForm.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    LeftNavigation: typeof import('./components/LeftNavigation.vue')['default']
    ReservationCard: typeof import('./components/reservation/ReservationCard.vue')['default']
    ReservationForm: typeof import('./components/reservation/ReservationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
