/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/BatchReservationPage': RouteRecordInfo<'/BatchReservationPage', '/BatchReservationPage', Record<never, never>, Record<never, never>>,
    '/CalendarPage': RouteRecordInfo<'/CalendarPage', '/CalendarPage', Record<never, never>, Record<never, never>>,
    '/DeviceEditPage': RouteRecordInfo<'/DeviceEditPage', '/DeviceEditPage', Record<never, never>, Record<never, never>>,
    '/DeviceListPage': RouteRecordInfo<'/DeviceListPage', '/DeviceListPage', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/SettingsPage': RouteRecordInfo<'/SettingsPage', '/SettingsPage', Record<never, never>, Record<never, never>>,
  }
}
